#!/usr/bin/expect -f

set timeout -1

spawn qemu-system-x86_64 --enable-kvm -kernel vmlinux -append "console=ttyS0 root=/dev/nvme0n1 init=/sbin/sh" -smp 1 -m 1G  -display none -serial stdio -drive file=testdisk.img,if=none,id=nvme -device nvme,drive=nvme,serial=disk -no-reboot

expect "~ # "
send "echo hi\n"

expect "~ # "
send "echo hi2\n"

expect "~ # "
send "ls\n"

expect "~ # "
send "reboot -f\n"
